# Generated by Django 4.2.3 on 2023-07-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biznews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_details',
            name='sub_details',
            field=models.TextField(null=True),
        ),
    ]
