# Generated by Django 4.2.3 on 2023-07-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biznews', '0002_news_details_sub_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_details',
            name='Tags',
            field=models.ManyToManyField(to='Biznews.tag'),
        ),
        migrations.AddField(
            model_name='news_details',
            name='sub_image',
            field=models.ImageField(null=True, upload_to='thumbnail'),
        ),
        migrations.AddField(
            model_name='news_details',
            name='third_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news_details',
            name='third_image',
            field=models.ImageField(null=True, upload_to='thumbnail'),
        ),
        migrations.AddField(
            model_name='news_details',
            name='third_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
