# Generated by Django 4.2.3 on 2023-07-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biznews', '0003_news_details_tags_news_details_sub_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_details',
            name='Tags',
            field=models.ManyToManyField(blank=True, to='Biznews.tag'),
        ),
    ]
