# Generated by Django 4.2.3 on 2023-07-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biznews', '0004_alter_news_details_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
