# Generated by Django 4.2.3 on 2023-07-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biznews', '0008_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thumbnail')),
                ('article', models.TextField()),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='News_Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thumbnail')),
                ('article', models.TextField()),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
