# Generated by Django 4.2.3 on 2023-07-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biznews', '0009_featured_news_news_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flickr_Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='Popular_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
