# Generated by Django 4.2.3 on 2023-07-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biznews', '0010_flickr_photos_popular_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(null=True, upload_to='thumbnail'),
        ),
    ]
